### ISSUE TITLE
Problem with Spring Hateoas in Spring Boot 2.2.0

### ISSUE THREAD

**Issue by AnhTuan-AiT** [paulcwarren/spring-content#520]
First, thanks for creating such a great project like spring-content. I ran into a problem when integrating spring-content into my project. I am using `content-fs-spring-boot-starter`, `spring-content-rest-boot-starter` (both have version 1.2.2) and `spring-boot` 2.2.0. I want to save the video file to the file system, and at the same time save the metadata file in PostgresSQL. I followed your instructions at [this](https://paulcwarren.github.io/spring-content/spring-content-rest-docs/), but when I sent the POST request to `http://localhost: 8080/files/`, then the phenomenon happens is that the metadata file is still saved to the DB, but the HTTP response doesn't return the same way as in the guides but `java.lang.NoSuchMethodError: org.springframework.hateoas.server.core.LinkBuilderSupport.<init>(Lorg/springframework/web/util/UriComponents;)V`. Then I try to send request to `http://localhost:8080/files/{id}`, with the id taken directly from the DB, the exception `Could not retrieve metadata` throwed. Looking forward to receiving feedback and early fixes from you
P/s: I use [this](https://paulcwarren.github.io/spring-content/refs/release/0.12.0/rest-index.html#_entity_resources) type of resource

**Comment by paulcwarren** [comment]
Hi @AnhTuan-AiT, 

Our v1.2.2 is designed to work with Spring Boot 2.4.  That is likely your problem I think.  IIRC Spring Boot 2.3 pulled in v1.0.0 of the Spring HATEOAS project that was entirely backward incompatible changes.

You can check Spring Boot compatibility in [this table](https://paulcwarren.github.io/spring-content/#reference-documentation).  If you are tied to Spring Boot 2.2 then you would need our version 1.0.0.M10.

HTH

**Comment by AnhTuan-AiT** [comment]
Hi @paulcwarren, thanh for your response, I tried with version 1.0.0.M10, even some other version but the error still occurred. I will try again one more time and response the result for you. Thanh you so much

**Comment by AnhTuan-AiT** [comment]
I also have some question:
1. Can I use Spring Content Rest to stream file which is normal file (.doc, .pdf,...), not video file, or I must use Spring Content Filesystem, write controller and do all the stuff of streaming file. If spring content REST can do this.
2. If I use Entity Resource of spring content REST, can I change the folder where files stored, e.g. my filesystem root is D://, I want store video files in subfolder D://videos/. Now, I see that spring content REST only saves my video files in D://, I can't find any info about whether it support for storing file in subfolder of root folder.
I'm looking forward to see your response along with some sample code, if it can

**Comment by paulcwarren** [comment]
Hi @AnhTuan-AiT, 

I had to make quite a few updates which I will try and enumerate here but I decided it was easier to commit a revised version of your code [here](https://github.com/paulcwarren/anhtuan-ait-example).

The changes I made are as follows:
- application.yaml; had to add `initialization-mode: always` to get it to create the schema
- application.yaml; added `?sslmode=disable` to the end of the jdbc url - only relevant if you ever used postgres as the content store (currently using filesystem).
- application.yaml; added `ddl-auto: create` to get it to create schema
- pom.xml; bumped Spring Boot to 2.2.13.RELEASE to resolve originally reported `java.lang.NoSuchMethodError` issue
- pom.xml; removed `<scope>test</scope>` from the `spring-content-fs-boot-starter` dependency
- pom.xml; removed the `spring-content-fs` dependency - unrequired
- pom.xml; remove the `h2` dependency - unrequired
- pom.xml; changed to `spring-content-rest-boot-starter` version of the rest starter project. content-xyz versions are effectively deprecated
- SpringContent.java; remove the `@EnableFilesystemStores` - unrequired.  Spring boot autoconfiguration enables the store
- SpringContentApplication.java; added `@ConfigurationPropertiesScan` - this was needed after bump to SB 2.2.13
- Video.java; added additional properties - name, summary and created in order to capture this metadata sent from the client (see files.js)
- VideoContentStore.java; added `@StoreRestResource(path="files")` to put the video content store controllers it in the same "uri space" as the spring data controllers (required by files.js)

HTH

**Comment by paulcwarren** [comment]
In answer to your questions:

> Can I use Spring Content Rest to stream file which is normal file (.doc, .pdf,...), not video file, or I must use Spring Content Filesystem, write controller and do all the stuff of streaming file. If spring content REST can do this.
Spring Content REST is designed to work over any storage module; fs, s3, etc and can transfer any content regardless of type; words docs, pdfs, videos.  The client determines if the content is streamed; videos, some pdfs depending on size versus just transferred in their entirety in one go.  The REST layer will also never load the entire content into memory - another common mistake made by custom implementations.

> If I use Entity Resource of spring content REST, can I change the folder where files stored, e.g. my filesystem root is D://, I want store video files in subfolder D://videos/. Now, I see that spring content REST only saves my video files in D://, I can't find any info about whether it support for storing file in subfolder of root folder.
Yes, please see committed code.  I changed the store by modifying your `content.fs.filesystemRoot` property.  Please note, the filesystem storage module's auto-configuration offers its [own property](https://paulcwarren.github.io/spring-content/refs/release/1.0.0.M10/fs-index.html#_spring_boot_configuration) (`spring.content.fs.filesystemRoot`) for configuring the root of your storage so you don;t actually need to provide your own.  

> In this example, how name and summary updated. We can do it through API which spring content REST generated or I must explicit write code.
[files.js](https://github.com/paulcwarren/spring-content-gettingstarted/blob/a15f3872c61f055ba1579467ae9838c97bf9b4cc/spring-content-fs/complete/src/main/resources/static/files.js#L25) send up those values to the server.  I added those properties into the Video entity so they now get captured properly. 

HTH

**Comment by AnhTuan-AiT** [comment]
Thank you @paulcwarren for your very detail response. I really appreciate your dedication to helping me solve the problem. Now, it works :)). But I want to be more clarified for my first 2 questions.:

Question 1: I know that spring content can store any kind of content in filesystem and the strategy which never  load the entire content into memory is a good way to go. Here, I have 2 question:

1. I want to know the way spring content stream file, does it use a buffer behind the sence? If you don't want to answer this question, I can find out for myself how you do it through the source code of spring content project on GitHub.

2. If i want to implement a feature allow to download a large file (e.g. size of 3GB) from server to client. I implemented a solution by myself to stream file. I use a buffer, StreamingBodyResponse and set `Content-Disposition` header to trigger default downloader of browser to download the file, save it on filesystem of client. So, if my file is normal file (e.g. pdf, zip,..), not media file (e.g. video, audio,...), does spring content REST can provide a similary feature?

P/s:  On the client side, to call this API, I use the form POST request instead of AJAX. That's because if I use AJAX it doesn't seem to be able to activate Chorme's default downloader, instead AJAX will cache the file into the browser's BLOB memory partition. And then I have to do one more thing to enable the default browser downloader to "download" the file from the BLOB partition and save it to the location the user chooses.

Question 2: I think I'm asking a question that isn't clear :(( I want store all content in a folder, e.g. `D://`. I chose this folder as my `filesystemRoot`. In this folder, for example, I want store my video files in subfolder: `D://videos/`, store my image files in subfolder: `D://images`, etc. So, if i change `content.fs.filesystemRoot` property, only my filesystem root changes from `D://` to another folder, that is not I want. Thing I want is spring content REST know that it must save my video file in subfolder `videos` of root folder `D://`, save my image in subfolder `images` of root folder `D://`, etc. Do spring content REST support this behavior?

**Comment by paulcwarren** [comment]
Hi @AnhTuan-AiT ,

#1 The whole thing is quite complicated as there are different types of request that need to be supported.  Regular requests, byte range requests and also various headers that have to be honored.  But, at its core, for regular requests it's actually quite simple.  Stores return a Spring Resource that in turn returns an InputStream (for reading).  And the request exposes an OutputStream that the client reads.  The input stream (content being read from storage) is copied, via a buffer, to the output stream (being read by the client).  That's it.   Everything else is built on that premise.

#2  this should be possible.  You can add the `@OriginalFilename` annotation to your entity and that will capture the filename sent by the client.  You can then[ register a Spring converter with your filesystem store](https://paulcwarren.github.io/spring-content/refs/release/1.2.2/fs-index.html#_storage_customization) that reads the original filename field and generates a path (within the store) to store the content.  So, for example, if client sends a file (myvideo.mpeg), your converter can generate a path `/videos/myvideo.mpeg`.

**Comment by AnhTuan-AiT** [comment]
Thank you very much, hope you are constantly passionate to develop useful things for the community like this
